name: stem-transfer-of-information
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - ipywidgets
  - matplotlib
  - colorspacious
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
